### PR TITLE
Use top-level mint http module for http1 connections

### PR DESCRIPTION
**Pull request by keathley**

### CODE REVIEW

**Review by sneako — APPROVED** [review]

**Comment by ericmj** [comment]
I don't think this will work correctly unless you include the proxy config in the pool key. If you make a first request to `https://google.com` over the proxy `example.com` then a connection will be opened in the pool to `example.com` with the key `{:https, "google.com", 443}`. A subsequent request to `https://google.com` without using the proxy options will use the config since the same pool key is used.

The reason the `Mint.HTTP1` and `Mint.HTTP2` modules do not do have the proxying logic is because pools likely need to reimplement some of it. Just like how pools need to reimplement the protocol version negotiating in `Mint.HTTP`.

**Comment by sneako** [comment]
@ericmj I could be missing something here, but isn't the only way to provide any conn_opts, including proxy config, to pass them under the pool key when starting Finch?

**Comment by ericmj** [comment]
I see, you are right. I was misunderstanding how the options were passed around for the different functions. I guess there is no way to set the proxy options per each request then? If you use the default pool, then only one proxy can be used for all those requests, correct?

There are resource usage optimizations you can do for proxies that might be worth to do. It looks like the connection pool for a proxy can only proxy for one host, unless using the default pool, but proxies can proxy requests for multiple different hosts.

**Comment by keathley** [comment]
> I guess there is no way to set the proxy options per each request then

This would have to be something we'd implement in Finch itself right? Mint also doesn't allow you to do this so it would have to be implemented at a higher level, which I think is what you're getting at.

> If you use the default pool, then only one proxy can be used for all those requests, correct?

Correct. I'm not sure if there's much to do about that from Finch's perspective. My thinking is that its "working as intended". But maybe I'm not seeing the issue.

Maybe I'm misunderstanding, but if you want to use a single proxy for multiple hosts, wouldn't you just set the proxy configuration in each pool definition? I feel like I don't quite understand the problem.

**Comment by sneako** [comment]
I guess it would probably be more efficient to share a proxy connection pool for these request that are against different hosts, but use the same proxy configuration, instead of starting a separate pool for each host...

**Comment by keathley** [comment]
Ah yeah, I see what you mean now. Ok, I'll think on that a bit. For now I'm going to go ahead and get this merged in to fix the #90. We can try to think about whether or not this is a use case we want to support.

**Pull request merged**
